enum LocaleType { en, ja, mn }

extension LocaleTypeExtension on LocaleType {
  static final typeNames = {
    LocaleType.en: 'EN',
    LocaleType.ja: 'JP',
    LocaleType.mn: 'MN',
  };

  String get label => typeNames[this]!;

  static final typeIds = {
    LocaleType.en: 'en',
    LocaleType.ja: 'ja',
    LocaleType.mn: 'mn',
  };
  static final flagIds = {
    LocaleType.ja: 'ja',
    LocaleType.en: 'uk',
    LocaleType.mn: 'mn',
  };

  String get id => typeIds[this]!;
  String get flagID => flagIds[this]!;
}

String listProj = """
[
  {
    "index": 1,
    "date": 2025,
    "nameMn": "Хагас дамжуулагч төхөөрөмжийн загвар  өргөдлийн систем ",
    "nameJP": "申請システム",
    "name": "Application System for Semiconductor Designers",
    "type": "Web",
    "position": "SE/TL",
    "skill": "Python-Django,Vue.js",
    "db": "MariaDB",
    "descriptionMn": "Хагас дамжуулагчийн дизайнеруудад зориулсан төхөөрөмжийн тохиргоо хийх өргөдлийн системийн хөгжүүлэлт - Төрөл бүрийн өргөдөл, баталгаажуулалт төхөөрөмжийн хуваарилалтыг зохицуулах системийн хөгжүүлэлт, баримт бичгийн боловсруулалт, нэвтрүүлэх ажиллагаанд оролцсон.",
    "description": "Developed an application system for configuring devices used by semiconductor designers. Participated in system development, document preparation, and deployment process.",
    "descriptionJP": "半導体設計者向けのデバイス設定アプリケーションシステムを開発しました。システム開発、ドキュメント作成、導入プロセスに参加しました。",
    "image": "",
    "other skills": "VS Code , Jenkins, win SCP",
    "link": ""
  },
  {
    "index": 2,
    "date": 2025,
    "nameMn": "Үйлдвэрлэлийн удирдлагын систем",
    "nameJP": "製造管理システム\\n",
    "name": "Aluminum Production Flow Monitoring and Verification System",
    "type": "Web",
    "position": "SE/TL",
    "skill": "Java, JSP, JS",
    "db": "IBM DB2",
    "descriptionMn": "Хөнгөн цагаан үйлдвэрлэлийн урсгалыг хянах баталгаажуулах систем - хөгжүүлэлт, баримт бичгийг загварчилах ажлыг хариуцсан.",
    "description": "Responsible for development and documentation design for a verification system that monitors the aluminum production flow.",
    "descriptionJP": "アルミニウム生産フローを監視する検証システムの開発および設計を担当しました。",
    "image": "",
    "other skills": "Eclipse, RSI",
    "link": ""
  },
  {
    "index": 3,
    "date": 2023,
    "nameMn": "Англи хэл бие даан сурах платформ",
    "nameJP": "英語自習プラットフォーム",
    "name": "IELTS Preperation System for Learners",
    "type": "Web",
    "position": "PM/SE",
    "skill": "Dart, Node.js",
    "db": "Firebase RTDB",
    "descriptionMn": "Суралцагчдад зориулсан IELTS дасгал ажиллах систем - Эхнээс нь дуустал бие даан хөгжүүлсэн.",
    "description": "Developed an IELTS practice system from scratch.",
    "descriptionJP": "IELTS練習システムをゼロから独自に開発しました。",
    "image": "",
    "other skills": "Firbase Hosting, Auth, Stripe",
    "link": "ielts.hishig-edu.com"
  },
  {
    "index": 4,
    "date": 2024,
    "nameMn": "Гишүүнчлэлийн систем",
    "nameJP": "会員システム\\n",
    "name": "User Registration System",
    "type": "Web",
    "position": "SE/TL",
    "skill": "Vue.js, Flutter, Java, Typescipt",
    "db": "AWS Aurora、PostGre SQL",
    "descriptionMn": "Хэрэглэгчийн бүртгэлийн процессийг автоматжуулах систем - Бааз болон системийг загварчилж хөгжүүлэлтэд гар бие оролцсон.",
    "description": "Modeled and participated in database design and system development for automating user registration processes.",
    "descriptionJP": "ユーザー登録プロセスを自動化するシステムのデータベース設計および開発に携わりました。",
    "image": "",
    "other skills": "VS Code, AWS,Keycloack",
    "link": ""
  },
  {
    "index": 5,
    "date": "2021-2024",
    "nameMn": "Зочид буудал удирдлагын систем",
    "nameJP": "施設管理システム\\nホテルや宿探しシステムの開発、OTAインテグレーション（Booking、Jaran、Rakutenなど）",
    "name": "Hotel Management System",
    "type": "Web, Desktop",
    "position": "SE/TL/PM",
    "skill": "Flutter, C#, Java(Spring boot)",
    "db": "AWS　Aurora、MySQL",
    "descriptionMn": "Зочид буудлын үйл ажиллагааг удирдах систем - Баазын бүтэц, баримт бичиг, хөгжүүлэлтийг удирдан гүйцэтгэсэн. Мөн OTA нэгтгэх ажлыг хариуцан гүйцэтгэсэн.",
    "description": "Managed database structure, documentation, and development of a hotel management system. Responsible for OTA integration.(Booking, Rakuten etc)",
    "descriptionJP": "ホテル管理システムのデータベース構造設計、ドキュメント作成、開発を管理しました。OTA（Booking、楽天等）統合を担当しました。",
    "image": "",
    "other skills": "VS Code, AWS , Jenkins, putty",
    "link": ""
  },
  {
    "index": 6,
    "date": 2023,
    "nameMn": "Япон хэлний цахим толь бичиг",
    "nameJP": "辞書",
    "name": "Japanese Dictionary",
    "type": "web",
    "position": "PM/SE",
    "skill": "Dart, Node.js",
    "db": "",
    "descriptionMn": "Япон хэл суралцагчидад зориулсан толь бичиг - Хайлтын системийг бие даан хөгжүүлсэн.",
    "description": "Developed a Japanese dictionary tailored for Mongolian learners.",
    "descriptionJP": "モンゴル学習者向けの日本語辞書を開発しました。",
    "image": "",
    "other skills": "",
    "link": "hishig-toli.com"
  },
  {
    "index": 7,
    "date": 2023,
    "nameMn": "Мэдээний сайт",
    "nameJP": "情報サイト",
    "name": "Educational Website for Learners",
    "type": "web",
    "position": "PM/SE",
    "skill": "Dart, Node.js",
    "db": "Firebase RTDB",
    "descriptionMn": "Анли болон япон хэлний мэдээний сайт - Бие даан хөгжүүлсэн.",
    "description": "Developed a bilingual news website in English and Japanese.",
    "descriptionJP": "英語・日本語を並ぶ方法を教えるニュースサイトを開発しました。",
    "image": "",
    "other skills": "",
    "link": "news.hishig-edu.com"
  },
  {
    "index": 8,
    "date": 2023,
    "nameMn": "Япон хэл бие даан сурах платформ",
    "nameJP": "日本語自習プラットフォーム",
    "name": "Self study Platform for Japanese Language Learners",
    "type": "web",
    "position": "PM/SE",
    "skill": "Dart, Node.js",
    "db": "Firebase RTDB",
    "descriptionMn": "Япон хэл суралцагчидад зориулсан дасгал ажлын платформ - Эхнээс нь дуустал бие даан хөгжүүлсэн. Төлбөрийн системийг Stripe тай нэгтгэсэн.",
    "description": "Developed a Japanese language exercise platform from scratch and integrated Stripe for payment processing. Supports both Mongolian and English languages.",
    "descriptionJP": "日本語学習プラットフォームを開発し、Stripe決済システムを統合しました。モンゴル語・英語対応のシステム",
    "image": "",
    "other skills": "Firbase Hosting, Auth, Stripe",
    "link": "jlpt.hishig-edu.com"
  },
  {
    "index": 9,
    "date": 2021,
    "nameMn": "Рестораны удирдлагын систем",
    "nameJP": "レストラン管理システム",
    "name": "Restaurant System",
    "type": "Web, Desktop, Mobile",
    "position": "SE/TL",
    "skill": "Flutter, Java",
    "db": "AWS　Aurora、MySQL",
    "descriptionMn": "Core хөгжүүлэлтийг хариуцан ажилласан.",
    "description": "Responsible for core development and maintenance.",
    "descriptionJP": "Core開発と保守を担当しました。",
    "image": "",
    "other skills": "VS Code, AWS EC 2, lambda, CI/CD, Jenkins, Firebase",
    "link": ""
  },
  {
    "index": 10,
    "date": 2020,
    "nameMn": "Машин даатгалын систем",
    "nameJP": "\\"\\"HoQ\\"\\"　保険システム",
    "name": "Vehicle Insurance Management System",
    "type": "Desktop",
    "position": "SE/TL",
    "skill": "C#",
    "db": "MSAccess",
    "descriptionMn": "Хэрэглэгчийн шаардлагад нийцүүлэн баримт бичгийг боловсруулж хөгжүүлэлтийг удирдан явуулсан.",
    "description": "Prepared documents according to client requirements and managed development tasks.",
    "descriptionJP": "顧客要件に基づきドキュメントを作成し、開発作業を管理しました。",
    "image": "",
    "other skills": "Visual　Studio",
    "link": ""
  },
  {
    "index": 11,
    "date": 2020,
    "nameMn": "Бизнесийн удирдлагын систем",
    "nameJP": "\\"\\"HotBridge\\"\\"　業務管理システム",
    "name": "Business Management System",
    "type": "Web",
    "position": "SE",
    "skill": "PHP, Java",
    "db": "MSSql",
    "descriptionMn": "Компанийн дотоод, үйл ажиллагааны тайлан, процессийг хянах системийн сайжруулалт дээр ажилласан.",
    "description": "Worked on improving internal systems for monitoring company operations and reporting processes.",
    "descriptionJP": "会社の内部業務監視および報告プロセスの改善に従事しました。",
    "image": "",
    "other skills": "Visual　Studio",
    "link": ""
  },
  {
    "index": 12,
    "date": 2019,
    "nameMn": "Бизнесийн удирдлагын систем",
    "nameJP": "\\"\\"びぶれ\\"\\"　業務管理システム",
    "name": "Operations Management System",
    "type": "Web",
    "position": "SE",
    "skill": "C#",
    "db": "Oracle",
    "descriptionMn": "Компанийн дотоод, үйл ажиллагааны тайлан, процессийг хянах системийн сайжруулалт дээр ажилласан.",
    "description": "Worked on improving internal systems for monitoring company operations and reporting processes.",
    "descriptionJP": "会社の内部業務監視および報告プロセスの改善に従事しました。",
    "image": "",
    "other skills": "Visual　Studio",
    "link": ""
  },
  {
    "index": 13,
    "date": 2019,
    "nameMn": "Өгөгдөл татах, илгээх",
    "nameJP": "\\"\\"重要予測\\"\\"　データ取込と送るバッチ",
    "name": "Data Processing batch",
    "type": "Batch",
    "position": "SE/TL",
    "skill": "Java",
    "db": "Oracle, MySql",
    "descriptionMn": "Систем хооронд өгөгдөл илгээх болон татах нэгтгэх Batch файлын хөгжүүлэлт, автоматжуулалт, гүйцэтгэлийг сайжруулах ажлыг хариуцан ажилласан.",
    "description": "Developed and automated batch files for data transmission and synchronization between systems, improving performance.",
    "descriptionJP": "システム間のデータ送受信および同期のためのバッチファイルを開発・自動化し、パフォーマンスを改善しました。",
    "image": "",
    "other skills": "Eclipse,Spring,\\nTerasoluna",
    "link": ""
  },
  {
    "index": 14,
    "date": 2019,
    "nameMn": "Худалдан авалтын систем",
    "nameJP": "\\"\\"TOGO\\"\\"　販売システム",
    "name": "Sales and Financial Reporting System",
    "type": "Web",
    "position": "SE",
    "skill": "Java, JavaScript",
    "db": "Oracle, MySql",
    "descriptionMn": "Худалдан авалт, орлого зарлагын тайлангийн хөгжүүлэлт дээр ажилласан.",
    "description": "Developed modules for procurement and financial reporting systems.",
    "descriptionJP": "調達および財務報告システムのモジュールを開発しました。",
    "image": "",
    "other skills": "Eclipse,Struts,Jsp",
    "link": ""
  },
  {
    "index": 15,
    "date": 2019,
    "nameMn": "Худалдан авалтын систем Handy",
    "nameJP": "\\"\\"SARES\\"\\"　販売のアプリ/ハンディ/",
    "name": "Handy Procurement System",
    "type": "Web",
    "position": "SE",
    "skill": "TypeScript",
    "db": "MSSql",
    "descriptionMn": "Худалдан авалтын системийн Handy хөгжүүлэлт дээр ажилласан.",
    "description": "Developed features for the sale system (Handy).",
    "descriptionJP": "販売システム（Handy）の機能を開発しました。",
    "image": "",
    "other skills": "Eclipse",
    "link": ""
  },
  {
    "index": 16,
    "date": 2018,
    "nameMn": "Худалдан авалтын систем",
    "nameJP": "\\"\\"SARES\\"\\"　販売システム",
    "name": "Sales and Financial Reporting System",
    "type": "Web",
    "position": "SE",
    "skill": "VB",
    "db": "MSSql",
    "descriptionMn": "Худалдан авалт, орлого зарлагын тайлангийн хөгжүүлэлт дээр ажилласан.",
    "description": "Responsible for maintenance and configuration of the Yamaha audio distribution calculation system.",
    "descriptionJP": "ヤマハ音響配信計算システムの保守と設定を担当しました。",
    "image": "",
    "other skills": "Visual　Studio",
    "link": ""
  },
  {
    "index": 17,
    "date": 2018,
    "nameMn": "Хөгжмийн систем",
    "nameJP": "\\"\\"YAMAHA\\"\\" 音楽のアブリ",
    "name": "Yamaha Audio Distribution Management System",
    "type": "Desktop",
    "position": "SE",
    "skill": "C#, C++",
    "db": "MSSql",
    "descriptionMn": "Yamaha хөгжмийн дууны тархалтыг тооцоолох тохиргооны системийн засвар үйлчилгээг хариуцан ажилласан.",
    "description": "Handled maintenance of Yamaha's audio distribution configuration system.",
    "descriptionJP": "ヤマハ音響配信設定システムの保守を担当しました。",
    "image": "",
    "other skills": "Visual　Studio",
    "link": ""
  },
  {
    "index": 18,
    "date": 2017,
    "nameMn": "Бизнесийн упирдлагын систем",
    "nameJP": "業務管理システム",
    "name": "Operations Management System",
    "type": "Web",
    "position": "PG",
    "skill": "Cake PHP, JavaScript, Css, Jquery, Bootstrap",
    "db": "PostGreSQL ",
    "descriptionMn": "Бараа бүтээгдэхүүний хүргэлтийн професийг хянах систем - Засвар үйлчилгээ, сайжруулалт хөгжүүлэлт дээр ажилласан.",
    "description": "Worked on maintenance and enhancement of a system for monitoring product delivery processes.",
    "descriptionJP": "商品配送プロセスを監視するシステムの保守・改善に従事しました。",
    "image": "",
    "other skills": "Eclipse, Apache",
    "link": ""
  },
  {
    "index": 19,
    "date": 2017,
    "nameMn": "Хүргэлтийн систем",
    "nameJP": "配送システム: 計画配送",
    "name": "Delivery Tracking System",
    "type": "Mobile",
    "position": "",
    "skill": "JavaScript",
    "db": "PostGreSQL, SqLite",
    "descriptionMn": "Бараа бүтээгдэхүүний хүргэлтийн професийг хянах систем - Засвар үйлчилгээ, сайжруулалт хөгжүүлэлт дээр ажилласан.",
    "description": "Worked on maintenance, improvement, and development of the product delivery process tracking system.",
    "descriptionJP": "商品配送プロセス追跡システムの保守、改善、開発に従事しました。",
    "image": "",
    "other skills": "Eclipse, Android Studio",
    "link": ""
  },
  {
    "index": 20,
    "date": 2017,
    "nameMn": "Хүргэлтийн систем GPS хяналт",
    "nameJP": "配送アプリケーションGPS",
    "name": "GPS Tracking System for Distributors",
    "type": "Mobile",
    "position": "SE/PM",
    "skill": "JavaScript",
    "db": "PostGreSQL, SqLite",
    "descriptionMn": "Түгээгчийн байршлыг хянах GPS хяналтын систем - GPS ашиглан мобайлаас хянах, бааз руу өгөгдөл дамжуулах мобайл апп хөгжүүлсэн.",
    "description": "Developed a mobile application for monitoring distributor locations using GPS and transmitting data to the database.",
    "descriptionJP": "GPSを使用して販売員の位置を監視し、データベースに送信するモバイルアプリを開発しました。",
    "image": "",
    "other skills": "Eclipse, Android Studio",
    "link": ""
  },
  {
    "index": 21,
    "date": 2017,
    "nameMn": "Техник ашиглалтын систем",
    "nameJP": "\\"\\"Odoo\\"\\" Technic Usage モバイルアプリケーション",
    "name": "Technical Registration and Monitoring System",
    "type": "Mobile",
    "position": "SE/PM",
    "skill": "Python, JavaScript",
    "db": "PostGreSQL, SqLite",
    "descriptionMn": "Техникийн бүртгэл, хяналтын систем - Баримт бичиг боловсруулах, таблетний Core хөгжүүлэлтийг хийсэн.",
    "description": "Created system documents and developed the core tablet module.",
    "descriptionJP": "要件定義、設計書を作成し、タブレット用コアモジュールを開発しました。",
    "image": "",
    "other skills": "",
    "link": ""
  },
  {
    "index": 22,
    "date": 2017,
    "nameMn": "Хүргэлт захиалгын систем",
    "nameJP": "\\"\\"Odoo\\"\\" Sale",
    "name": "Order Delivery Management app",
    "type": "Mobile,Web",
    "position": "SE/TL",
    "skill": "Python, Java, Swift",
    "db": "PostGreSQL, SqLite",
    "descriptionMn": "Түгээгч нарт зориулсан гар утасны хөгжүүлэлтийг хийсэн.",
    "description": "Developed a mobile application for managing order deliveries.",
    "descriptionJP": "注文配達管理のためのモバイルアプリを開発しました。",
    "image": "",
    "other skills": "Eclipse, Android Studio, X code",
    "link": ""
  },
  {
    "index": 23,
    "date": 2017,
    "nameMn": "Автобусны буудлын систем",
    "nameJP": "Bus stop",
    "name": "Bus Route Search App",
    "type": "Mobile",
    "position": "",
    "skill": "JavaScript",
    "db": "",
    "descriptionMn": "Мобайл сургалтад зориулан автобусны буудлын чиглэл хайх утасны апп хөгжүүлсэн.",
    "description": "Developed a mobile app for searching bus routes for mobile training.",
    "descriptionJP": "モバイル研修用のバスルート検索アプリを開発しました。",
    "image": "",
    "other skills": "",
    "link": ""
  },
  {
    "index": 24,
    "date": 2016,
    "nameMn": "Хөгжүүлэгчийн tool",
    "nameJP": "\\"\\"研究\\"\\"",
    "name": "Developer tool",
    "type": "Desktop",
    "position": "SE",
    "skill": "C#",
    "db": "",
    "descriptionMn": "",
    "description": "",
    "descriptionJP": "",
    "image": "",
    "other skills": "",
    "link": ""
  },
  {
    "index": 25,
    "date": "2016-2017",
    "nameMn": "HCM Mobile",
    "nameJP": "\\"\\"Human Resource System\\"\\" モバイルアプリケーション",
    "name": "HR Management System (Mobile Version)",
    "type": "Mobile",
    "position": "SE/TL",
    "skill": "JavaScript",
    "db": "MSSQL ",
    "descriptionMn": "Хүний нөөц удирдлагын систем - хяналт баталгаажуулалтын хэсгийн мобайл хувилбарыг хөгжүүлсэн.",
    "description": "Developed the mobile version of the HR management system.",
    "descriptionJP": "人事管理システムのモバイル版を開発しました。",
    "image": "",
    "other skills": "人事管理システム－管理決定と確認,プロセス制御のアプリケーション",
    "link": ""
  },
  {
    "index": 26,
    "date": 2016,
    "nameMn": "Бараа материалын менежментийн систем",
    "nameJP": "\\"\\"Retail\\"\\" POS",
    "name": "Inventory system",
    "type": "Desktop",
    "position": "SE",
    "skill": "C#, JAVA",
    "db": "MSSQL ",
    "descriptionMn": "Баримт бичгийн дагуу хөгжүүлэлт, засварыг хариуцан ажилласан.",
    "description": "Responsible for development and maintenance according to documentation.",
    "descriptionJP": "ドキュメントに基づく開発と保守を担当しました。",
    "image": "",
    "other skills": "小売店にも活用頂ける機能を拡充。\\n在庫管理システムとの連動やバンドル販売等",
    "link": ""
  },
  {
    "index": 27,
    "date": 2015,
    "nameMn": "POS систем",
    "nameJP": "\\"\\"SETSEN\\"\\" POS",
    "name": "POS System",
    "type": "Desktop",
    "position": "SE",
    "skill": "C#, JAVA",
    "db": "MSSQL, MySql ",
    "descriptionMn": "Кассын системийн хөгжүүлэлт дээр ажилласан.",
    "description": "Participated in the development and maintenance of a POS system.",
    "descriptionJP": "POSシステムの開発および保守に参加しました。",
    "image": "",
    "other skills": ".NET , VISUAL STUDIO, DevExp,XAMARIN, Eclipse Java EE",
    "link": ""
  },
  {
    "index": 28,
    "date": 2014,
    "nameMn": "Хүний нөөц удирдлагын систем",
    "nameJP": "\\"\\"DIAMOND ERP 6 - HCM\\"\\"",
    "name": "HR Management System",
    "type": "Desktop",
    "position": "SE/TL",
    "skill": "C#, JAVA",
    "db": "MSSQL ",
    "descriptionMn": "МТА -н хүнийн нөөцийн удирдлагын системийн хөгжүүлэлт дээр ажиллаж амжилттай нэвтрүүлсэн.",
    "description": "Contributed to the successful development and deployment of the HR management system for the tax authority.",
    "descriptionJP": "税務当局向けの人事管理システムの開発および導入に成功裏に貢献しました。",
    "image": "",
    "other skills": "人事管理システム/HCM/",
    "link": ""
  },
  {
    "index": 29,
    "date": "2013-2014",
    "nameMn": "ERP систем",
    "nameJP": "\\"\\"DIAMOND\\"\\" ERP",
    "name": "ERP system",
    "type": "Desktop",
    "position": "SE",
    "skill": "C#, JAVA",
    "db": "MSSQL,Oracle, MySql",
    "descriptionMn": "Системийн алдаа, сайжруулалт, тайлангийн хөгжүүлэлт дээр ажилласан.",
    "description": "Worked on system error resolution, feature enhancements, and report development.",
    "descriptionJP": "システムの不具合修正、機能改善、レポート開発に従事しました。",
    "image": "",
    "other skills": "モジュールの修正.\\n業務統合パッケージ - 「最新のIT(インフォメーションテクノロジー）を活用した、受注から出荷までの一連のサプライチェーンと管理会計、財務開会人事管理を含めた企業の基幹業務を支援する統合情報システム」",
    "link": ""
  },
  {
    "index": 30,
    "date": 2013,
    "nameMn": "Хөдөлгөөн лекц（Sample）",
    "nameJP": "フラッシュプログラミングは教育方法論のため",
    "name": "Interactive Lecture Samples",
    "type": "Desktop",
    "position": "PG",
    "skill": "JavaScript",
    "db": "-",
    "descriptionMn": "Баримт бичгийн боловсруулалт хийж хөдөлгөөнт лекцийн жишээг javascript ашиглан хөгжүүлсэн.",
    "description": "Created requirements, design documentation and developed interactive lecture examples using JavaScript.",
    "descriptionJP": "要件定義や設計書などのドキュメントを作成し、JavaScriptを使用してインタラクティブな講義例を開発しました。",
    "image": "",
    "other skills": "Adobe Flash\\nAdobe After Effects\\nAdobe PhotoShop",
    "link": ""
  }
]
""";

// String listProj = '[{"name": "John", "age": 30}, {"name": "Doe", "age": 25}]';
String listProjS = '''
[
  {
    "index": 1,
    "date": "2025",
    "nameMn": "Хагас дамжуулагч төхөөрөмжийн загвар  өргөдлийн систем ",
    "nameJP": "申請システム\\nシステムの基本設計、開発\\n",
    "name": "Application system\\nBasic design and development of the system\\n",
    "type": "Web",
    "position": "SE/TL",
    "skill": "Python-Django,Vue.js",
    "db": "MariaDB",
    "description": "半導体の設計作業者に関する各種申請ソフトウェア\\n社内で活用しているワークフローの刷新を行います。​\\n半導体の設計作業者にアカウント作成・権限設定・実行環境（コンピュートファーム(CF)）設定などを実現するための各種申請出せるシステム：\\nEDA（Electronic Design Automation​）利用申請\\nCFグループ利用申請\\nログインアカウント申請\\nパスワードリセット申請",
    "other skills": "VS Code , Jenkins, win SCP"
  },
  {
    "index": 2,
    "date": "2025",
    "nameMn": "Үйлдвэрлэлийн удирдлагын систем",
    "nameJP": "製造管理システム\\n",
    "name": "Production management system\\n",
    "type": "Web",
    "position": "SE/TL",
    "skill": "Java,JSP, JS",
    "db": "IBM DB2",
    "description": "製造システムの改善\\n・アルミニウムの加工のライン製造マシンの処理。\\n・客先の希望に合わせて制作できるかどうかのテスト。　\\n・機能のアップグレード、バグ修正\\\t\\\t\\\t\\\t\\\t\\\tRole：システムの基本設計、開",
    "other skills": "Eclipse, RSI"
  }
]
  ''';
String listProjDel = """
[
    {
      "index": 1,
      "date": "2025",
      "nameMn": "Хагас дамжуулагч төхөөрөмжийн загвар  өргөдлийн систем ",
      "nameJP": "申請システム\\nシステムの基本設計、開発\\n",
      "name": "Application system\\nBasic design and development of the system\\n",
      "type": "Web",
      "position": "SE/TL",
      "skill": "Python-Django,Vue.js",
      "db": "MariaDB",
      "description": "半導体の設計作業者に関する各種申請ソフトウェア\\n社内で活用しているワークフローの刷新を行います。​\\n半導体の設計作業者にアカウント作成・権限設定・実行環境（コンピュートファーム(CF)）設定などを実現するための各種申請出せるシステム：\\nEDA（Electronic Design Automation​）利用申請\\nCFグループ利用申請\\nログインアカウント申請\\nパスワードリセット申請",
      "other skills": "VS Code , Jenkins, win SCP"
    },
    {
      "index": 2,
      "date": "2025",
      "nameMn": "Үйлдвэрлэлийн удирдлагын систем",
      "nameJP": "製造管理システム\\n",
      "name": "Production management system\\n",
      "type": "Web",
      "position": "SE/TL",
      "skill": "Java,JSP, JS",
      "db": "IBM DB2",
      "description": "製造システムの改善\\n・アルミニウムの加工のライン製造マシンの処理。\\n・客先の希望に合わせて制作できるかどうかのテスト。　\\n・機能のアップグレード、バグ修正\\t\\t\\t\\t\\t\\tRole：システムの基本設計、開",
      "other skills": "Eclipse, RSI"
    },
    {
      "index": 3,
      "date": "2023",
      "nameMn": "Англи хэл бие даан сурах платформ",
      "nameJP": "英語自習プラットフォーム",
      "name": "English self study platform",
      "type": "Web",
      "position": "PM/SE",
      "skill": "Dart, Node.js",
      "db": "Firebase RTDB",
      "other skills": "Firbase Hosting, Auth, Stripe",
      "link": "ielts.hishig-edu.com"
    },
    {
      "index": 4,
      "date": "2024",
      "nameMn": "Гишүүнчлэлийн систем",
      "nameJP": "会員システム\\n",
      "name": "Membership system",
      "type": "Web",
      "position": "SE/TL",
      "skill": "Vue.js, Flutter, Java, Typescipt",
      "db": "AWS　Aurora、PostGre SQL",
      "description": "会員システムの要件定義、基本設計、開発",
      "other skills": "VS Code, AWS,Keycloack"
    },
    {
      "index": 5,
      "date": "2021-2024",
      "nameMn": "Байгууламжийн удирдлагын систем",
      "nameJP": "施設管理システム\\nホテルや宿探しシステムの開発、OTAインテグレーション（Booking、Jaran、Rakutenなど）",
      "name": "Facility management system",
      "type": "Web, Desktop",
      "position": "SE/TL/PM",
      "skill": "Flutter, C#, Java, spring boot",
      "db": "AWS　Aurora、MySQL",
      "description": "Development of hotel and accommodation search system, OTA integration (Booking, Jaran, Rakuten, etc.)\\nお客さんよう注文アプリ（Tablet）、ウェイター用注文アプリ（モバイル）、注文監視（デスクトップapp）\\n技術：FireBase、AWS　EC2、Aurora、Flutter、Jenkins、CI/CD",
      "other skills": "VS Code, AWS , Jenkins, putty"
    },
    {
      "index": 6,
      "date": "2023",
      "nameMn": "Толь бичиг",
      "nameJP": "辞書",
      "name": "Dictionary(JP-MN, MN-JP)",
      "type": "web",
      "position": "PM/SE",
      "skill": "Dart, Node.js",
      "link": "hishig-toli.com"
    },
    {
      "index": 7,
      "date": "2023",
      "nameMn": "Мэдээний сайт",
      "nameJP": "情報サイト",
      "name": "Educational blog site",
      "type": "web",
      "position": "PM/SE",
      "skill": "Dart, Node.js",
      "db": "Firebase RTDB",
      "link": "news.hishig-edu.com"
    },
    {
      "index": 8,
      "date": "2023",
      "nameMn": "Япон хэл бие даан сурах платформ",
      "nameJP": "日本語自習プラットフォーム",
      "name": "Japanese self study platform",
      "type": "web",
      "position": "PM/SE",
      "skill": "Dart, Node.js",
      "db": "Firebase RTDB",
      "other skills": "Firbase Hosting, Auth, Stripe",
      "link": "jlpt.hishig-edu.com"
    },
    {
      "index": 9,
      "date": "2021",
      "nameMn": "Рестораны удирдлагын систем",
      "nameJP": "レストラン管理システム",
      "name": "Restaurant management system",
      "type": "Web, Desktop, Mobile",
      "position": "SE/TL",
      "skill": "Flutter, Java",
      "db": "AWS　Aurora、MySQL",
      "other skills": "VS Code, AWS EC 2, lambda, CI/CD, Jenkins, Firebase"
    },
    {
      "index": 10,
      "date": "2020",
      "nameMn": "Даатгалын систем",
      "nameJP": "\\"HoQ\\"　保険システム",
      "name": "Insurance system(HoQ )",
      "type": "Desktop",
      "position": "SE/TL",
      "skill": "C#",
      "db": "MSAccess",
      "other skills": "Visual　Studio"
    },
    {
      "index": 11,
      "date": "2020",
      "nameMn": "Бизнесийн удирдлагын систем",
      "nameJP": "\\"HotBridge\\"　業務管理システム",
      "name": "Business management system(HotBridge )",
      "type": "Web",
      "position": "SE",
      "skill": "PHP, Java",
      "db": "MSSql",
      "other skills": "Visual　Studio"
    },
    {
      "index": 12,
      "date": "2019",
      "nameMn": "Бизнесийн удирдлагын систем",
      "nameJP": "\\"びぶれ\\"　業務管理システム",
      "name": "Vibre Business management system",
      "type": "Web",
      "position": "SE",
      "skill": "C#",
      "db": "Oracle",
      "other skills": "Visual　Studio"
    },
    {
      "index": 13,
      "date": "2019",
      "nameMn": "Өгөгдөл татах, илгээх",
      "nameJP": "\\"重要予測\\"　データ取込と送るバッチ",
      "name": "Data Processing batch",
      "type": "Batch",
      "position": "SE/TL",
      "skill": "Java",
      "db": "Oracle, MySql",
      "other skills": "Eclipse,Spring,\\nTerasoluna"
    },
    {
      "index": 14,
      "date": "2019",
      "nameMn": "Худалдан авалтын систем",
      "nameJP": "\\"TOGO\\"　販売システム",
      "name": "TOGO Sales system",
      "type": "Web",
      "position": "SE",
      "skill": "Java,JavaScript",
      "db": "Oracle, MySql",
      "other skills": "Eclipse,Struts,Jsp"
    },
    {
      "index": 15,
      "date": "2019",
      "nameMn": "Худалдан авалтын систем",
      "nameJP": "\\"SARES\\"　販売のアプリ/ハンディ/",
      "name": "SARES Sales app/handy/",
      "type": "Web",
      "position": "SE",
      "skill": "スクリプト言語",
      "db": "MSSql",
      "other skills": "Eclipse"
    },
    {
      "index": 16,
      "date": "2018",
      "nameMn": "Худалдан авалтын систем",
      "nameJP": "\\"SARES\\"　販売システム",
      "name": "SARES Sales system",
      "type": "Web",
      "position": "SE",
      "skill": "VB",
      "db": "MSSql",
      "other skills": "Visual　Studio"
    },
    {
      "index": 17,
      "date": "2018",
      "nameMn": "Хөгжмийн систем",
      "nameJP": "\\"YAMAHA\\" 音楽のアブリ",
      "name": "YAMAHA Music app",
      "type": "Desktop",
      "position": "SE",
      "skill": "C#,C++",
      "db": "MSSql",
      "other skills": "Visual　Studio"
    },
    {
      "index": 18,
      "date": "2017",
      "nameMn": "Худалдан авалтын систем",
      "nameJP": "業務管理システム",
      "name": "Business management system",
      "type": "Web",
      "position": "PG",
      "skill": "Cake PHP, JavaScript, Css, Jquery, Bootstrap",
      "db": "PostGreSQL ",
      "other skills": "Eclipse, Apache"
    },
    {
      "index": 19,
      "date": "2017",
      "nameMn": "Хүргэлтийн систем",
      "nameJP": "配送システム: 計画配送",
      "name": "Delivery system",
      "type": "Mobile",
      "skill": "JavaScript",
      "db": "PostGreSQL, SqLite",
      "description": "Plan delivery",
      "other skills": "Eclipse, Android Studio"
    },
    {
      "index": 20,
      "date": "2017",
      "nameMn": "Хүргэлтийн систем GPS хяналт",
      "nameJP": "配送アプリケーションGPS",
      "name": "GPS tracking",
      "type": "Mobile",
      "position": "SE/PM",
      "skill": "JavaScript",
      "db": "PostGreSQL, SqLite",
      "other skills": "Eclipse, Android Studio"
    },
    {
      "index": 21,
      "date": "2017",
      "nameMn": "Техник ашиглалтын систем",
      "nameJP": "\\"Odoo\\" Technic Usage モバイルアプリケーション",
      "name": "Technic Usage Administration",
      "type": "Mobile",
      "position": "SE/PM",
      "skill": "Python, JavaScript",
      "db": "PostGreSQL, SqLite",
      "description": "農業機械管理: 技術的な作業命令、修理、点検、登録など"
    },
    {
      "index": 22,
      "date": "2017",
      "nameMn": "Хүргэлт захиалгын систем",
      "nameJP": "\\"Odoo\\" Sale",
      "name": "Sale",
      "type": "Mobile,Web",
      "position": "SE/TL",
      "skill": "Python, Java, Swift",
      "db": "PostGreSQL, SqLite",
      "description": "モバイルアプリケーション: 購入、受注、受注の請求書",
      "other skills": "Eclipse, Android Studio, X code"
    },
    {
      "index": 23,
      "date": "2017",
      "nameMn": "Автобусны буудлын систем",
      "nameJP": "Bus stop",
      "name": "Bus stop",
      "type": "Mobile",
      "skill": "JavaScript"
    },
    {
      "index": 24,
      "date": "2016",
      "nameMn": "Хөгжүүлэгчийн tool",
      "nameJP": "\\"研究\\"",
      "name": "Developer tool",
      "type": "Desktop",
      "position": "SE",
      "skill": "C#",
      "description": "DataContract 作成アプリケーション , システムログ検索アプリケーション,   報告する研究など"
    },
    {
      "index": 25,
      "date": "2016-2017",
      "nameMn": "HCM Mobile",
      "nameJP": "\\"Human Resource System\\" モバイルアプリケーション",
      "name": "Human Resource System Mobile application",
      "type": "Mobile",
      "position": "SE/TL",
      "skill": "JavaScript",
      "db": "MSSQL ",
      "description": "Xamarin",
      "other skills": "人事管理システム－管理決定と確認,プロセス制御のアプリケーション"
    },
    {
      "index": 26,
      "date": "2016",
      "nameMn": "Бараа материалын менежментийн систем",
      "nameJP": "\\"Retail\\" POS",
      "name": "Inventory",
      "type": "Desktop",
      "position": "SE",
      "skill": "C#, JAVA",
      "db": "MSSQL ",
      "other skills": "小売店にも活用頂ける機能を拡充。\\n在庫管理システムとの連動やバンドル販売等"
    },
    {
      "index": 27,
      "date": "2015",
      "nameMn": "POS систем",
      "nameJP": "\\"SETSEN\\" POS",
      "name": "POS",
      "type": "Desktop",
      "position": "SE",
      "skill": "C#, JAVA",
      "db": "MSSQL, MySql ",
      "description": "キャッシュレジスターシステム",
      "other skills": ".NET , VISUAL STUDIO, DevExp,XAMARIN, Eclipse Java EE"
    },
    {
      "index": 28,
      "date": "2014",
      "nameMn": "HCM",
      "nameJP": "\\"DIAMOND ERP 6 - HCM\\"",
      "name": "HCM",
      "type": "Desktop",
      "position": "SE/TL",
      "skill": "C#, JAVA",
      "db": "MSSQL ",
      "other skills": "人事管理システム/HCM/"
    },
    {
      "index": 29,
      "date": "2013-2014",
      "nameMn": "\\"DIAMOND\\" ERP",
      "nameJP": "\\"DIAMOND\\" ERP",
      "name": "DIAMOND ERP",
      "type": "Desktop",
      "position": "SE",
      "skill": "C#, JAVA",
      "db": "MSSQL,Oracle, MySql",
      "other skills": "モジュールの修正.\\n業務統合パッケージ - 「最新のIT(インフォメーションテクノロジー）を活用した、受注から出荷までの一連のサプライチェーンと管理会計、財務開会人事管理を含めた企業の基幹業務を支援する統合情報システム」"
    },
    {
      "index": 30,
      "date": "2013",
      "nameJP": "フラッシュプログラミングは教育方法論のため",
      "name": "Flash programming is for educational methodology",
      "type": "Desktop",
      "position": "PG",
      "skill": "JavaScript",
      "db": "-",
      "description": "Adobe Flashで作った可動の「心理学のレッスン」",
      "other skills": "Adobe Flash\\nAdobe After Effects\\nAdobe PhotoShop"
    }
  ]""";
